name: GFSLT-VLP-AVRET
data:
  train_label_path: ./data/features/ph14t_features.train
  dev_label_path: ./data/features/ph14t_features.dev
  test_label_path: ./data/features/ph14t_features.test
  max_length: 400
training:
  wandb: disabled # online or disabled
  scale_embedding: False
model:
  transformer:  ./pretrain_models/MBart_trimmed
  visual_encoder: ./pretrain_models/mytran   # mytran
  sign_proj: True
